### ISSUE TITLE
sub modules are not availble

### ISSUE THREAD

**Issue by z160896** [alistairewj/bert-deid#12]
I try to test your bert-deid package. encountered a few issues. Please help, give me feedbacks on these. Thanks

1) I try to test your package using Python3. module, Transformer, is not available from 'from bert_deid.model import'

**Comment by alistairewj** [comment]
Yeah unfortunately the current version is pretty broken. I've actually done a lot of updates to make it work with more recent versions of transformers if you check out the `updates` branch. I'm still in the process of publishing the model itself on PhysioNet but I'm hopeful that will finish in the next week or two.

**Comment by z160896** [comment]
> Yeah unfortunately the current version is pretty broken. I've actually done a lot of updates to make it work with more recent versions of transformers if you check out the `updates` branch. I'm still in the process of publishing the model itself on PhysioNet but I'm hopeful that will finish in the next week or two.

Hi Alisaire, Thank you for your response. Now I got output_preds.py work using your trained bert model. For train_transformer.py, it need pydeid package. I install the package, but it has no modules like annotation, annotators etc. I could not find the source code for pydeid from github. How can I get this issue solved. Thanks, very much appreciate. Robert

**Comment by alistairewj** [comment]
Yes it really should not depend on pydeid. That package is currently not public. I would try `train_ner.py` - but no guarantees it will work. I am hoping to fix this up in the next few weeks!

**Comment by knightperfectionist** [comment]
> Yes it really should not depend on pydeid. That package is currently not public. I would try `train_ner.py` - but no guarantees it will work. I am hoping to fix this up in the next few weeks!

Hey @alistairewj @z160896 , any progress on pydeid package??

**Comment by knightperfectionist** [comment]
> I try to test your bert-deid package. encountered a few issues. Please help, give me feedbacks on these. Thanks
> 
> 1. I try to test your package using Python3. module, Transformer, is not available from 'from bert_deid.model import'

```from bert_deid.model.transformer import Transformer``` would resolve the error, though pydeid packgae is required in order to run output script

@z160896 @alistairewj

**Comment by tompollard** [comment]
> Hey @alistairewj @z160896 , any progress on pydeid package??

This is my bad...it is waiting on me to finish some things up. I'm in the process of moving the package to Spacy and expect to finish soon, at which point it will be open sourced.

**Comment by alistairewj** [comment]
I merged the updates branch and it should work now, I realize I bumped the version in a semantically incorrect way but hopefully it's still usable. Please raise any new issues you run into.
